node{

notify('Started')
// This change is made by Amit Vashist  
  
stage('Git Checkout') {
  git branch: 'main', credentialsId: '01', url: 'https://github.com/amitvashisttech/devops-ericsson-08-Feb-2021.git'
}

def project_path = "02-App-Code/petclinic-code"

dir(project_path) {

stage('Maven Clean') {
sh 'mvn clean'
}

stage('Maven Compile') {
sh 'mvn compile'
}

stage('Maven Test') {
sh 'mvn test'
}

stage('Maven Package') {
sh 'mvn package'
}

stage('Tomcat Deployment') {
 deploy adapters: [tomcat8(credentialsId: '02', path: '', url: 'http://172.31.0.101:8080/')], contextPath: 'petclinic', onFailure: false, war: 'target/petclinic.war'
    
  }
 }
 notify('Completed')
} 

def notify(status){
  emailext(
    to: "amitvashist7@outlook.com",
    subject: "${status}: JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
    body: """<p> ${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
             <p> Check Console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME}[${env.BUILD_NUMBER}]</a></p>""",
  )
}
